server {
    listen 80;
    server_name localhost;

    location /app/ {
        # Point to the folder where the files actually landed
        alias /usr/share/nginx/html/app/skillforge/;
        index index.html;
        try_files $uri $uri/ /app/index.html;
    }

    location / {
        return 301 /app/;
    }
}
